import Head from "next/head";
import { useSelector } from "react-redux";
import Feed from "../components/Feed";
import Header from "../components/Header";
import Modal from "../components/Modal";

export default function Home() {
  const modalselect = useSelector((state) => state.modal.value);

  return (
    <div className=" h-screen w-screen overflow-y-scroll bg-gray-100 ">
      <Head>
        <title>Instagram-Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      <Header />

      {modalselect && <Modal />}

      {/* feed */}
      <Feed />
      {/* footer */}
    </div>
  );
}
